language: node_js

os:
  - linux

node_js:
  - "8"

script:
  - npm install
  - npm run build
  - npm run test

deploy:
  on: master
  provider: surge
  project: ./public/
  domain: steveworley.surge.sh
  skip_cleanup: true

branches:
  only:
    - master