language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "8"

script:
  - npm install
  - gatsby build
  - npm run test

deploy:
  provider: surge
  project: './public'
  domain: steveworley.surge.sh